package:
  name: treeshrink
  version: v1.3.9

source:
  #path: ../../
  git_rev: master
  git_url: https://github.com/uym2/TreeShrink.git
requirements:
  host:
    - python  >=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0
    - setuptools
    - r-base >=4.0

  run:
    - python  >=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0
    - r-base >=4.0

test:
  imports:
    - treeshrink

about:
  home: https://github.com/uym2/TreeShrink
  license: GNU GENERAL PUBLIC LICENSE
  license_file: LICENSE
