>cox11.p1 GENE.cox11~~cox11.p1  ORF type:internal len:192 (+),score=247.79 cox11:3-575(+)
ALSLYIRITLAQPNGSFLEYNHHFYNVIVTGHAFIMIFFMVMPILIGGFGNWFVPLMIGA
PDMAFPRMNNISFWLLPPSLLLLVESVLCEAGVGTGWTVYPPLSGIIAHSGGAVDLAIFS
LHLSGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFLTAILLLLSLPVLAGAITML
LTDRNFNTTFF
>cox110.p1 GENE.cox110~~cox110.p1  ORF type:internal len:237 (+),score=320.38 cox110:3-710(+)
GYFSTNHKDIGTLYLIFAAISGIAGTVLSLYIRATLASPNSGFLDNNYHLYNVIVTGHAF
IMVFFLVMPALIGGFGNWFVPLMIGAPDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGVG
TGWTVYPPLAGITAHSGGSVDLAIFSLHLSGAASILGAINFICTITNMRAKSLPFHRLPL
FAWAIYITAFLLLLSLPVLAGAITMLLTDRNFNTTFFDPAGGGDPVLYQHLFWFFG
>cox111.p1 GENE.cox111~~cox111.p1  ORF type:internal len:241 (+),score=249.29 cox111:1-720(+)
GAPDMAFPRMNNISFWLLPPSLLLLVESILCEAGVGTGWTVYPPLSGITAHSGGSVDLAI
FSLHLSGAASILGAINFICTIVNMRTKNLAFHRLPLFVWSIFITAILLLLSLPVLAGAIT
MLLTDRNFNTTFFDPAGGGDPVLYQHLFWFFGHPEVYILILPGFGIISHIVVSAARKPIF
GYLGMVYAMLSIGILGFIVWAHHMYTVGLDIDTRAYFTAATMIIAIPTGIKVFSWLATLW
>cox112.p1 GENE.cox112~~cox112.p1  ORF type:internal len:206 (+),score=294.37 cox112:1-615(+)
ALSMYIRTSLAQPNSDFFDYNYHLYNVVVTGHAFVMIFFMVMPALIGGFGNWFVPLMIGA
PDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGVGTGWTVYPPLSSITAHSGGAVDLAIFS
LHLSGAASILGAINFICTITNMRAKSLPFHRLPLFAWAIFLTAFLLLLSLPVLAGAITML
LTDRNFNTTFFDPAGGGDPVLYQHL
>cox113.p1 GENE.cox113~~cox113.p1  ORF type:internal len:202 (+),score=211.23 cox113:1-603(+)
SGIAGTALSLYIRITLAQPNGSFLEYNHHFYNVIITGHAILMIFFMVMPILIGGFGNWFV
PLMIGAPDMAFPRMNNISFWLLPPSLLLLIESVLCEAGVGTGWTVYPPLSGVIAHSGGSV
DLAIFSLHLSGAASILGAINFICTIVNMRTQSLPFHKLPLFVWSVFITAILLLLSLPVLA
GAITMLLTDRNFNTTFFDPAG
>cox114.p1 GENE.cox114~~cox114.p1  ORF type:internal len:232 (+),score=283.82 cox114:1-693(+)
TIKDIGTLYIIFGGIAGVAGTALSLYIRITLSQPNGNFLEYNHHFYNVIVTGHAFVMIFF
MVMPVLIGGFGNWLVPLMIGAPDMAFPRMNNISFWLLPPSLLLLIESVLCEAGVGTGWTV
YPPLSGIIAHSGGAVDLAIFSLHLSGAASILGAINFICTIINMRTESLPFHKLPLFVWAV
FITAILLLLSLPVLASAITMLLADRNFNTTFFDPAGGGDPVLYQHLFWFFG
>cox115.p1 GENE.cox115~~cox115.p1  ORF type:3prime_partial len:188 (+),score=275.96 cox115:1-561(+)
MLSIYIRATLAVPNSNFLDYNYHLYNVIVTGHALLMVFFLVMPALIGGFGNWFVPLMIGA
PDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGVGTGWTVYPPLSGITAHSGGSVDLAIFS
LHLSGAASILGAINFICTITNMRAKSLPFHRLPLFAWSIFITAFLLLLSLPVLAGAITML
LTDRNFN
>cox116.p1 GENE.cox116~~cox116.p1  ORF type:internal len:206 (+),score=309.20 cox116:1-615(+)
ALSLYIRSTLASPDSNFLDYNFHLYNVIVTGHAFIMVFFMVMPALIGGFGNWFVPLMIGA
PDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGVGTGWTVYPPLAGITAHSGGAVDLAIFS
LHLSGAASILGAINFICTITNMRAKSLPFHRLPLFAWSIFITAFLLLLSIPVLAGAITML
LTDRNFNTTFFDPAGGGDPVLYQHL
>cox117.p1 GENE.cox117~~cox117.p1  ORF type:internal len:194 (+),score=266.19 cox117:1-579(+)
ALSLYMRLTLATPDSNFMEHNYHLYNVVVTGHAFIMVFFLVMPALIGGFGNWFVPLMIGA
PDMAFPRMNNISFWLLPPSLLLLVGSVLCEAGVGTGWTVYPPLAGITSHSGGAVDLAIFS
LHLAGAASILGAINFICTITNMRSKSLPFHRLPLFAWSIFITAFLLLLSLPVLAGAITML
LTDRNFNTTFFDP
>cox118.p1 GENE.cox118~~cox118.p1  ORF type:internal len:206 (+),score=302.37 cox118:1-615(+)
ALSLYIRSTLAYPNSNFLEYNYHLYNVIVTGHAFIMVFFLVMPALIGGFGNWFVPLMIGA
PDMAFPRMNNVSFWLLPPSLLLLIGSVLCEAGVGTGWTVYPPLAGITAHSGGAVDLAIFS
LHLAGAASILGAINFICTITNMRAKSLPFHRLPLFAWSIFITAFLLLLSLPVLAGAITML
LTDRNFNTTFFDPAGGGDPVLYQHL
>cox119.p1 GENE.cox119~~cox119.p1  ORF type:internal len:206 (+),score=305.30 cox119:1-615(+)
ALSLYIRATLATPNSNFLEYNYHLYNVIVTGHAFIMIFFMVMPALIGGFGNWFVPLMIGA
PDMAFPRMNNISFWLLPPSLLLLVGSVLCEAGVGTGWTVYPPLSGITAHSGGAVDLAIFS
LHLSGAASILGAINFICTITNMRSKSLPFHRLPLFVWAIFITAFLLLLSLPVLAGAITML
LTDRNFNTTFFDPAGGGDPVLYQHL
>cox12.p1 GENE.cox12~~cox12.p1  ORF type:internal len:188 (+),score=253.53 cox12:1-561(+)
VLSLYIRATLASPNSDFLEYNYHLYNVIITGHAFIMIFFLVMPALIGGFGNWFVPLMIGA
PDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGVGTGWTVYPPLSGITAHSGGSVDLAIFS
LHLSGAASLLGAINFICTITNMRAKSLPFHKLPLFAWAIYITAFLLLLSLPVLAGAITML
LTDRNFN
>cox120.p1 GENE.cox120~~cox120.p1  ORF type:internal len:206 (+),score=311.02 cox120:1-615(+)
ALSLYIRATLAYPGSNFLEYNYHLYNVIVTGHAFIMVFFMVMPALIGGFGNWFVPLMIGA
PDMAFPRMNNVSFWLLPPALLLLIGSVLCEAGVGTGWTVYPPLAGITSHSGGSVDLAIFS
LHLSGAASILGAINFICTITNMRAKSLPFHRLPLFVWSIFLTAFLLLLSIPVLAGAITML
LTDRNFNTTFFDPAGGGDPVLYQHL
>cox121.p1 GENE.cox121~~cox121.p1  ORF type:internal len:206 (+),score=264.27 cox121:1-615(+)
ALSLYIRLTLAVPNSNFMEHNYHLYNVIVTGHAFIMIFFMVMPALIGGFGNWFVPLMIGA
PDMAFPRMNNISFWLLPPSLLLLVGSVLCEAGVGTGWTVYPPLSGITAHSGGAVDLAIFS
LHLSGAASILGAINFICTITNMRSKSLPFHRLPLFAWSIFITAFLLLLSLPVLAGAITML
LTDRNFNTTFFDPAGGGDPVLYQHL
>cox122.p1 GENE.cox122~~cox122.p1  ORF type:internal len:206 (+),score=289.58 cox122:1-615(+)
ALSLYIRLTLAVPNSNFMEHNYHLYNVIVTGHAFIMIFFMVMPALIGGFGNWFVPLMIGA
PDMAFPRMNNISFWLLPPSLLLLVGSVLCEAGVGTGWTVYPPLSGITAHSGGAVDLAIFS
LHLSGAASILGAINFICTITNMRSKSLPFHRLPLFAWSIFITAFLLLLSLPVLAGAITML
LTDRNFNTTFFDPAGGGDPVLYQHL
>cox123.p1 GENE.cox123~~cox123.p1  ORF type:internal len:206 (+),score=272.89 cox123:1-615(+)
ALSLYIRSTLASPDSSFLDYNFHLYNVIVTGHAFIMVFFLVMPALIGGFGNWFVPLMIGA
PDMAFPRMNNVSFWLLPPSLLLLIGSVLCEAGVGTGWTVYPPLAGITVHSGGAVDLAIFS
LHLSGAASVLGAINFICTITNMRAKSLPFHRLPLFAWSIFLTAFLLLLSIPVLAGAITML
LTDRNFNTTFFDPAGGGDPILYQHL
>cox124.p1 GENE.cox124~~cox124.p1  ORF type:internal len:206 (+),score=279.90 cox124:1-615(+)
VLSLYIRSTLAYPNSNFLEYNYHLYNVIVTGHAFIMVFFLVMPALIGGFGNWFVPLMIGA
PDMAFPRMNNVSFWLLPPSLLLLIGSVLCEAGVGTGWTVYPPLAGITAHSGGAVDLAIFS
LHLAGAASILGAINFICTITNMRAKSLPFHRLPLFAWSIFITAFLLLLSLPVLAGAITML
LTDRNFNTTFFDPAGGGDPVLYQHL
>cox125.p1 GENE.cox125~~cox125.p1  ORF type:internal len:204 (+),score=305.94 cox125:1-609(+)
ALSLYIRSALAYPNSNFLEYNYHLYNVIVTGHAFIMVFFLVMPALIGGFGNWFVPLMIGA
PDMAFPRMNNVSFWLLPPSLLLLIGSVLCEAGVGTGWTVYPPLAGITAHSGGAVDLAIFS
LHLAGAASILGAINFICTITNMRAKSLPFHRLPLFAWSIFITAFLLLLSLPVLAGAITML
LTDRNFNTTFFDPAGGGDPVLYQ
>cox126.p1 GENE.cox126~~cox126.p1  ORF type:internal len:206 (+),score=286.51 cox126:1-615(+)
ALSLYIRATLAYPDSNFLDYNFHLYNVIVTGHAFIMIFFMVMPALIGGFGNWFVPLMIGA
PDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGVGTGWTVYPPLSSITAHSGGSVDLAIFS
LHLSGAASILGAINFICTITNMRAKSLPFHRLPLFAWAIFITAFLLLLSLPVLAGAITML
LTDRNFNTTFFDPAGGGDPVLYQHL
>cox127.p1 GENE.cox127~~cox127.p1  ORF type:internal len:206 (+),score=271.72 cox127:1-615(+)
ILSLYIRSTLAYPNSNFLEYNYHLYNVIVTGHAFIMVFFLVMPALIGGFGNWFVPLMIGA
PDMAFPRMNNVSFWLLPPSLLLLIGSVLCEAGVGTGWTVYPPLAGITAHSGGAVDLAIFS
LHLAGAASILGAINFICTITNMRAKSLPFHRLPLFAWSIFITAFLLLLSLPVLAGAITML
LTDRNFNTTFFDPAGGGDPVLYQHL
>cox128.p1 GENE.cox128~~cox128.p1  ORF type:internal len:206 (+),score=246.50 cox128:1-615(+)
ALSLYIRLTLAVPNSNFLEHNYHLYNVIVTGHAFIMIFFMVMPALIGGFGNWFIPLMIGA
PDMAFPRMNNISFWLLPPSLLLLVSSVLCEAGVGTGWTVYPPLSSITAHSGGAVDLAIFS
LHLSGAASILGAINFICTITNMRSKSLPFHRLPLFAWAIFITAFLLLLSLPVLAGAITML
LTDRNFNTTFFDPAGGGDPVLYQHL
>cox129.p1 GENE.cox129~~cox129.p1  ORF type:internal len:204 (+),score=268.86 cox129:1-609(+)
ALSLYIRLTLAVPNSNFMEHNYHLYNVIVTGHAFIMIFFMVMPALIGGFGNWFVPLMIGA
PDMAFPRMNNISFWLLPPSLLLLVGSVLCEAGVGTGWTVYPPLSGITAHSGGAVDLAIFS
LHLSGAASILGAINFICTITNMRSKSLPFHRLPLFAWSIFITAFLLLLSLPVLAGAITML
LTDRNFNTTFFDPAGGGDPVLYQ
>cox13.p1 GENE.cox13~~cox13.p1  ORF type:internal len:188 (+),score=257.81 cox13:1-561(+)
VLSLYIRATLLAPNSNFLDYNYHLYNVSVTGHAFLMVFFLVMPALIGGFGNWFVPLMIGA
PDMAFPRMNNISFWLLPPSILLFIGSVLCEAGVGTGWTVYPPLSGIASHSGGSVDLAIFS
FHLSGAASILGAINFICTITNMRAKGLPFHRLPLFAWSIYITAFLLILSLPVLAGAITML
LTDRNFN
>cox130.p1 GENE.cox130~~cox130.p1  ORF type:internal len:211 (+),score=299.79 cox130:1-630(+)
IGTLYLIFAAIAGLAGTMLSIYIRATLAVPNSNFLDYNYHLYNVIVTGHALLMVFFLVMP
ALIGGFGNWFVPLMIGAPDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGVGTGWTVYPPL
SGITAHSGGSVDLAIFSLHLSGAASILGAINFICTITNMRAKSLPFHRLPLFAWSIFITA
FLLLLSLPVLAGAITMLLTDRNFNTTFFDP
>cox131.p1 GENE.cox131~~cox131.p1  ORF type:internal len:224 (+),score=288.36 cox131:1-669(+)
IGTLYLIFAAVSGLAGTILSIYIRANLAVPNSNFLDYNYHFYNVIVTGHALIMVFFLVMP
ALIGGFGNWLVPLMIGAPDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGVGTGWTVYPPL
AGITAHSGGSVDLAIFSLHLSGAASILGAINFICTITNMRANSLPFHRLPLFVWSIFLTA
FLLLLSLPVLAGAITMLLTDRNFNTTFFDPAGGGDPVLYQHLF
>cox132.p1 GENE.cox132~~cox132.p1  ORF type:internal len:189 (+),score=211.85 cox132:2-565(+)
LYIRITLAQPNGGFLDYNHHFYNVVITGHALLMIFFMVMPILIGGFGNWFVPLMIGAPDM
AFPRMNNISFWLLPPSLLLLIESILCESGVGTGWTVYPPLSGVLSHSGGSVDLAIFSLHL
SGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLSLPVLAGAITMLLTD
RNFNTTFF
>cox133.p1 GENE.cox133~~cox133.p1  ORF type:internal len:198 (+),score=232.23 cox133:1-591(+)
TALSLYIRITLAQPNSSFLDYNHQFYNVVITGHALLMIFFMVMPILIGGFGNWFVPLMIG
APDMAFPRMNNISFWLLPPSLLLLIESILCESGVGTGWTIYPPLSSVLAHSGGSVDLAIF
SLHLSGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLSLPVLAGAITM
LLTDRNFNTTFFDPAGE
>cox134.p1 GENE.cox134~~cox134.p1  ORF type:internal len:189 (+),score=195.35 cox134:1-564(+)
LYIRITLAQPNSSFLDYNHHFYNVVITGHALLMIFFMVMPILIGGFGNWFVPLMIGAPDM
AFPRMNNISFWLLPPSLLLLIESILCESGVGTGWTVYPPLSGVLSHSGGSVDLAIFSLHL
SGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLSLPVLAGAITMLLTD
RNFNTTFF
>cox135.p1 GENE.cox135~~cox135.p1  ORF type:internal len:205 (+),score=235.43 cox135:1-612(+)
GIAGTALSLYIRITLAQPNGSFLDYNHQFYNVVITGHALLMIFFMVMPILIGGFGNWFVP
LMIGAPDMAFPRMNNISFWLLPPSLLLLIESILCEAGVGTGWTVYPPLSGVLSHSGGSVD
LAIFSLHLSGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLSLPVLAG
AITMLLTDRNFNTTFFDPAGGGDP
>cox136.p1 GENE.cox136~~cox136.p1  ORF type:internal len:196 (+),score=236.37 cox136:1-585(+)
ALSLYIRITLAQPNGGFLDYNHHFYNVVITGHALLMIFFMVMPILIGGFGNWFVPLMIGA
PDMAFPRMNNISFWLLPPSLLLLIESILCESGVGTGWTVYPPLSGVLSHSGGSVDLAIFS
LHLSGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLSLPVLAGAITML
LTDRNFNTTFFDPAG
>cox137.p1 GENE.cox137~~cox137.p1  ORF type:internal len:198 (+),score=236.68 cox137:1-591(+)
ALSLYIRITLAQPNGGFLDYNHHFYNVVITGHALLMIFFMVMPILIGGFGNWFVPLMIGA
PDMAFPRMNNISFWLLPPSLLLLIESILCESGVGTGWTVYPPLSGVLSHSGGSVDLAIFS
LHLSGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLSLPVLAGAITML
LTDRNFNTTFFDPAGGG
>cox138.p1 GENE.cox138~~cox138.p1  ORF type:internal len:216 (+),score=296.26 cox138:1-645(+)
GIAGTALSLYIRITLAQPNGGFLDYNHHFYNVVITGHALLMIFFMVMPILIGGFGNWFVP
LMIGAPDMAFPRMNNISFWLLPPSLLLLIESVLCEAGVGTGWTVYPPLSSVLSHSGGSVD
LAIFSLHLSGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLSLPVLAG
AITMLLTDRNFNTTFFDPAGGGDPVLFQHLFWFFG
>cox139.p1 GENE.cox139~~cox139.p1  ORF type:internal len:182 (+),score=233.28 cox139:1-543(+)
LYIRITLAQPNGSFLDYNHHFYNVVITGHALLMIFFMVMPILIGGFGNWFVPLMIGAPDM
AFPRMNNISFWLLPPSLLLLIESVLCEAGVGTGWTVYPPLSSVLSHSGGSVDLAIFSLHL
SGAASILGAINFICTIVNMRTESLPFHKLPLFVWSVFITAILLLLSLPVLAGAITMLLTD
R
>cox140.p1 GENE.cox140~~cox140.p1  ORF type:3prime_partial len:140 (+),score=175.45 cox140:3-419(+)
MAFPRMNNISFWLLPPSLLLLIESVLCEMGVGTGWTVYPPLSGVLAHSGGSVDLAIFSLH
LSGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLSLPVLAGAITMLLT
DRNFNTTFFDPAGGGDPVL
>cox141.p1 GENE.cox141~~cox141.p1  ORF type:internal len:162 (+),score=198.03 cox141:3-485(+)
GNWFVPLMIGAPDMAFPRMNNISFWLLPPSLLLLIESVLCEAGVGTGWTIYPPLSGVLSH
SGGSVDLAIFSLHLSGAASILGAINFICTIVNMRTESLPFHKLPLFVWSVFITAILLLLS
LPVLAGAITMLLTDRNFNTTFFDPAGGGDPVLFQHLFWFFG
>cox142.p1 GENE.cox142~~cox142.p1  ORF type:internal len:201 (+),score=261.65 cox142:1-600(+)
TALSLYIRITLAQPNGGFLDYNHHFYNVVITGHALLMIFFMVMPILIGGFGNWFVPLMIG
APDMAFPRMNNISFWLLPPSLLLLIESVLCEAGVGTGWTVYPPLSSVLSHSGGSVDLAIF
SLHLSGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLSLPVLAGAITM
LLTDRNFNTTFFDPAGGGDP
>cox143.p1 GENE.cox143~~cox143.p1  ORF type:internal len:216 (+),score=251.53 cox143:1-645(+)
GIAGTALSLYIRITLAQPNGGFLDYNYHXYNVVITGHALLMIFFMVMPILIGGFGNWFVP
LMIGAPDMAFPRMNNISXWLLPPSLLLLIESVLCEAGVGTGWTVYPPLSGVLSHSGGSVD
LAIFSLHLSGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLSLPVLAG
AITMLLTDRNFNTTFFDPAGGGDPVLFQHLFWFFG
>cox144.p1 GENE.cox144~~cox144.p1  ORF type:internal len:189 (+),score=195.35 cox144:1-564(+)
LYIRITLAQPNSSFLDYNHHFYNVVITGHALLMIFFMVMPILIGGFGNWFVPLMIGAPDM
AFPRMNNISFWLLPPSLLLLIESILCESGVGTGWTVYPPLSGVLSHSGGSVDLAIFSLHL
SGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLSLPVLAGAITMLLTD
RNFNTTFF
>cox145.p1 GENE.cox145~~cox145.p1  ORF type:internal len:216 (+),score=256.95 cox145:1-645(+)
GIAGTALSLYIRITLAQPNGGFLDYNHHFYNVVITGHALLMIFFMVMPILIGGFGNWFVP
LMIGAPDMAFPRMNNISFWLLPPSLLLLIESVLCEAGVGTGWTIYPPLSGVLSHSGGSVD
LAIFSLHLSGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLSLPVLAG
AITMLLTDRNFNTTFFDPAGGGDPVLFQHLFWFFG
>cox146.p1 GENE.cox146~~cox146.p1  ORF type:internal len:203 (+),score=247.17 cox146:1-606(+)
GIAGTALSLYIRITLAQPNGGFLDYNHHFYNVVITGHALLMIFFMVMPILIGGFGNWFVP
LMIGAPDMAFPRMNNISFWLLPPSLLLLIESVLCEAGVGTGWTVYPPLSSVLSHSGGSVD
LAIFSLHLSGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLSLPVLAG
AITMLLTDRNFNTTFFDPAGGG
>cox147.p1 GENE.cox147~~cox147.p1  ORF type:internal len:183 (+),score=210.43 cox147:1-546(+)
GTALSLYIRITLAQPNGGFLDYNHHFYNVVITGHALLMIFFMVMPILIGGFGNWFVPLMI
GAPDMAFPRMNNISFWLLPPSLLLLIESILCETGVGTGWTVYPPLSGVLSHSGGSVDLAI
FSLHLSGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLSLPVLAGAIT
ML
>cox148.p1 GENE.cox148~~cox148.p1  ORF type:3prime_partial len:154 (+),score=214.44 cox148:1-459(+)
MIFFMVMPILIGGFGNWFVPLMIGAPDMAFPRMNNISFWLLPPSLLLLIESVLCEAGVGT
GWTVYPPLSSVLSHSGGSVDLAIFSLHLSGAASILGAINFICTIVNMRTESLPFHKLPLF
VWSVFITAILLLLSLPVLAGAITMLLTDRNFNT
>cox149.p1 GENE.cox149~~cox149.p1  ORF type:internal len:189 (+),score=238.97 cox149:2-565(+)
LYIRITLAQPNGGFLDYNHHFYNVVITGHALLMIFFMVMPILIGGFGNWFVPLMIGAPDM
AFPRMNNISFWLLPPSLLLLIESVLCEAGVGTGWTVYPPLSSVLSHSGGSVDLAIFSLHL
SGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLSLPVLAGAITMLLTD
RNFNTTFF
>cox150.p1 GENE.cox150~~cox150.p1  ORF type:internal len:207 (+),score=268.41 cox150:1-618(+)
LYIRITLAQPNGGFLDYNHHFYNVVITGHALLMIFFMVMPILIGGFGNWFVPLMIGAPDM
AFPRMNNISFWLLPPSLLLLIESVLCEAGVGTGWTVYPPLSSVLSHSGGSVDLAIFSLHL
SGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLSLPVLAGAITMLLTD
RNFNTTFFDPAGGGDPVLFQHLFWFF
>cox151.p1 GENE.cox151~~cox151.p1  ORF type:internal len:147 (+),score=214.37 cox151:1-438(+)
PFKIGAPDMAFPRMNNISFWLLPPSLLLLIESILCEAGVGTGWTIYPPLSGVLSHSGGSV
DLAIFSLHLSGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLALPVLA
GAITMLLTDRNFNTTFFDPAGGGNPV
>cox152.p1 GENE.cox152~~cox152.p1  ORF type:internal len:208 (+),score=252.95 cox152:1-621(+)
TALSLYIRITLAQPNGSFLDYNHHFYNVVITGHALLMIFFMVMPILIGGFGNWFVPLMIG
APDMAFPRMNNISFWLLPPSLLLLIESVLCEAGVGTGWTVYPPLSSVLSHSGGSVDLAIF
SLHLSGAASILGAINFICTIVNMRTESLPFHKLPLFVWSVFITAILLLLSLPVLAGAITM
LLTDRNFNTTFFDPAGGGDPVLFQHLF
>cox153.p1 GENE.cox153~~cox153.p1  ORF type:internal len:189 (+),score=214.48 cox153:1-564(+)
LYIRITLAQPNGSFLDYNHHFYNVVITGHALLMIFFMVMPILIGGFGNWFVPLMIGAPDM
AFPRMNNISFWLLPPSLLLLIESVLCEAGVGTGWTVYPPLSGVLSHSGGSVDLAIFSLHL
SGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLALPVLAGAITMLLTD
RNFNTTFF
>cox154.p1 GENE.cox154~~cox154.p1  ORF type:internal len:189 (+),score=227.56 cox154:1-564(+)
LYIRITLAQPNGGFLDYNHQFYNVVITGHALLMIFFMVMPILIGGFGNWFVPLMIGAPDM
AFPRMNNISFWLLPPSLLLLIESILCEAGVGTGWTVYPPLSGVLSHSGGSVDLAIFSLHL
SGAASILGAINFICTIVNMRTESLPFHKLPLFVWAVFITAILLLLSLPVLAGAITMLLTD
RNFNTTFF
>cox155.p1 GENE.cox155~~cox155.p1  ORF type:internal len:201 (+),score=295.82 cox155:1-600(+)
GIAGTALSIYIRITLASPDSTFLDYNYHLYNVIVTGHAFLMIFFMVMPALIGGFGNWFVP
LMIGAPDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGVGTGWTVYPPLSSVTAHSGGAVD
LAIFSLHLSGAASILGAINFICTITNMRAKSLPFHRLPLFAWSIFITAFLLLLSLPVLAG
AITMLLTDRNFNTTFFDPAG
>cox156.p1 GENE.cox156~~cox156.p1  ORF type:internal len:222 (+),score=326.00 cox156:1-663(+)
FATVAGVAGTALSMYIRINLAQPNSDFLDYNYHLYNVIVTGHAXVMVFFMVMPALIGGFG
NWFVPLMIGAPDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGAGTGWTVYPPLAGITVHS
GGSVDLAIFSLHLSGAASILGAINFICTITNMRAKSLPFHRLPLFVWSIFITAFLLILSL
PVFAXAITMLLTDRNFNTTFFDPAGGGDPVLYQHLFWFFGH
>cox157.p1 GENE.cox157~~cox157.p1  ORF type:internal len:212 (+),score=320.27 cox157:2-634(+)
AAVAGVAGTALSMYIRISLAQPNSDFLDYNYHLYNVIVTGHAFVMIFFMVMPALIGGFGN
WFVPLMIGAPDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGAGTGWTVYPPLSSITSHSG
GSVDLAIFSLHLSGAASILGAINFICTITNMRSKSLPFHRLPLFVWSIFITAFLLVLSLP
VFAGAITMLLTDRNFNTTFFDPAGGGDPILY
>cox158.p1 GENE.cox158~~cox158.p1  ORF type:internal len:222 (+),score=307.00 cox158:2-664(+)
LYLIFAAVSGIAGTALSMYIRMTLARPDSDFLNYNHHLYNVIVTGHAFVMVFFLVMPALI
GGFGNWFVPLMIGAPDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGVGTGWTVYPPLAGI
TSHSGGSVDLAIFSLHLSGAASILGAINFICTITNMRAKSLPFHRLPLFVWSIFITAFLL
ILSLPVLAGAITMLLTDRNFNTTFFDPAGGGDPVLYQHLFW
>cox159.p1 GENE.cox159~~cox159.p1  ORF type:internal len:222 (+),score=284.44 cox159:2-664(+)
LYLIFAAVSGIAGTALSMYIRITLARPDSDFLNYNHHLYNVIVTGHAFVMVFFLVMPALI
GGFGNWFVPLMIGAPDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGVGTGWTVYPPLAGI
TSHSGGSVDLAIFSLHLSGAASILGAINFICTITNMRAKSLPFHRLPLFVWSIFITAFLL
ILSLPVLAGAITMLLTDRNFNTTFFDPAGGGDPVLYQHLFW
>cox160.p1 GENE.cox160~~cox160.p1  ORF type:internal len:217 (+),score=281.17 cox160:2-649(+)
LYLIFAAVSGIAGTALSMYIRITLARPDSDFLNYNHHLYNVIVTGHAFVMVFFLVMPALI
GGFGNWFVPLMIGAPDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGAGTGWTVYPPLSGI
TSHSGGSIDLAIFSLHLSGAASILGAINFICTITNMRAKSLPFHRLPLFVWSIFITAFLL
ILALPVLAGAITMLLTDRNFNTTFFDPAGGGDPVLY
>cox161.p1 GENE.cox161~~cox161.p1  ORF type:internal len:208 (+),score=255.22 cox161:1-621(+)
GVAGTALSMYIRITLAHPGSDFLDYNYHLYNVIVTGHAFVMVFFMVMPALIGGFGNWFVP
LMIGAPDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGAGTGWTVYPPLAGITAHSGGSID
LAIFSLHLSGAASILGAINFICTITNMRSKSLPFHRLPLFVWSIFITAFLLVLSLPVLAG
AITMLLTDRNFNTTFFDPAGGGDPVLY
>cox162.p1 GENE.cox162~~cox162.p1  ORF type:internal len:208 (+),score=278.87 cox162:1-621(+)
GVAGTALSMYIRIHLAQPSSDFLDYNYHLYNVIVTGHAFVMVFFMVMPALIGGFGNWFVP
LMIGAPDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGAGTGWTVYPPLAGITAHSGGSID
LAIFSLHLSGAASILGAINFICTITNMRAKSLPFHRLPLFVWSIFLTAFLLILSLPVLAG
AITMLLTDRNFNTTFFDPAGGGDPVLY
>cox163.p1 GENE.cox163~~cox163.p1  ORF type:internal len:219 (+),score=307.77 cox163:1-654(+)
FAAVAGVAGTALSMYIRINLAQPNSDFLDYNYHLYNVIVTGHAFVMVFFMVMPALIGGFG
NWFVPLMIGAPDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGAGTGWTVYPPLAGITAHS
GGSIDLAIFSLHLSGAASILGAINFICTITNMRAKSLPFHRLPLFVWSIFITAFLLILSL
PVFAGAITMLLTDRNFNTTFFDPAGGGDPVLYQHLFWF
>cox18.p1 GENE.cox18~~cox18.p1  ORF type:internal len:224 (+),score=302.66 cox18:3-671(+)
GCFSTNHKDIGTLYLIFAAISGIAGTVLSLYIRATLASPNSGFLDNNYHLYNVIVTGHAF
IMVFFLVMPALIGGFGNWFVPLMIGAPDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGVG
TGWTVYPPLAGITAHSGGSVDLAIFSLHLSGAASILGAINFICTITNMRAKSLPFHRLPL
FAWAIYITAFLLLLSLPVLAGAITMLLTDRNFNTTFFDPAGGG
>cox19.p1 GENE.cox19~~cox19.p1  ORF type:internal len:232 (+),score=284.07 cox19:3-695(+)
IGTLYLIFAAISGIAGTVLSLYIRATLASPNSGFLDNNYHLYNVIVTGHAFLMIFFLVMP
ALIGGFGNWFVPLMIGAPDMAFPRMNNISFWLLPPSLLLLIGSVLCEAGVGTGWTVYPPL
SGITAHSGGSVDLAIFSLHLSGAASILGAINFICTITNMRAKSLPFHRLPLFAWAIYITA
FLLLLSLPVLAGAITMLLTDRNFNTTFFDPAGGGDPVLYQHLFWFFGHPEV
